
[server]
# ファイル監視の除外設定
fileWatcherType = "auto"
headless = true

[browser]
# ブラウザ設定
gatherUsageStats = false

[theme]
# テーマ設定
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
